import { Inter } from "next/font/google";
import "./globals.css";
import { CategoryProvider } from "@/context/CategoryContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mx-auto max-w-screen-lg">
          <CategoryProvider>
            <div className="flex min-h-screen item4-center p-24">
              {children}
            </div>
          </CategoryProvider>
        </div>
      </body>
    </html>
  );
}
